openapi: 3.0.0
info:
  title: AI Gent Directory
  version: 0.0.0
tags: []
paths: {}
components: {}
servers:
  - url: https://aiagents.amber.io
    description: endpoint for ai agent directory
    variables: {}
